# Generated by Django 5.1.6 on 2025-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ngo',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
