# Generated by Django 5.1.6 on 2025-06-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0002_donor_photo_ngo_logo_volunteer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('loc', models.CharField(max_length=200)),
                ('volunteers_needed', models.IntegerField()),
                ('sDate', models.DateField()),
                ('eDate', models.DateField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.ngo')),
            ],
        ),
    ]
