# Generated by Django 5.1.6 on 2025-06-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0003_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Requested', max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.activity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.volunteer')),
            ],
        ),
    ]
