# Generated by Django 5.1.6 on 2025-06-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0005_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='don',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ngoapp.donor'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='vol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ngoapp.volunteer'),
        ),
    ]
