# Generated by Django 5.1.6 on 2025-06-18 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0006_subscribe_don_alter_subscribe_vol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ngodon', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.activity')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.donor')),
            ],
        ),
    ]
