# Generated by Django 5.1.6 on 2025-06-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0007_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
