# Generated by Django 5.1.6 on 2025-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0008_donations_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Use commas to separate multiple keywords, e.g. donate, donation', max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
