# Generated by Django 5.1.6 on 2025-06-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0010_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
